---
apiVersion: v1
kind: Secret
metadata:
 name: key
 namespace: dev-namespace
data:
 .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICIzODk0ODU1MDQxNzcuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsaGVrNDFVekJPU1dWc1pISmlNSGhEVDBVNVRHUXdaRFJPZW13MFZrWkJlRXN6UlROVVYwMTJXVmhLVTFSWVVtdGtiVWt6VlZOMFdWbHRTbXhpYkZaeVYxUmplVTVZUVhkYVYxSkVaREZrVTFKdFZucFRSVlpzVlcxc1MwNXJPSGRhU0ZJMFRXdDRURkZzYUZOT1IzZzFUV3hWTVZKSFJqQlhiVlV5V1RCRmVGRlZlRTFMTTBreVVWVTFXRXd5YUcxak1sWnBaSGs0TWxaclNtdGFia1pJVWtoS2FXUlVVa1JsYTFweVZXeEdWMWRGU214T1dHeHZUVEJOTW1KSFRtRk9la1pIVWtaR2JHSnNVa2RYYTFKV1RWZGthbVZYYkZGamVrNXRVV3BLYW1GVk5YTmhhMVpxVmtob1ExZFVUVEJSTVdoUlV6TnNNVmR1WjNoaVZVMDBWVEJrUlZwWVFtdE5iWE16VlRKUmVGSnVhM3BaVlU1S1ZWaHNWR0pIVmpaalZsWlVaREZDTWsxRlVqVmhiWEJTVW5wU1IxcERPVkJrVld4VlpHdHplbGxYVm01amJIQlNUMFJHZWxZd1ozcExNRlV3WWtaV1VWTkdWalZUU0d4dFUwUmthMHN4VW5CVVNFSk9UVVJLY0dKSE1VNVJlbEV6WldrNVZscDZSbHBqYkZwelZtMUtTV0pFU25wUlZVa3lUa2RXY0ZSdE1WUlVWM0JvWVc1V1IxcHVhR3RUYm5CYVUyNXdhRTVZWTNKWGEyeHBVakZTV0Zrd1ZqRlZNR2cxWTFWT2VtRlZkRmhrUlRCNFZtNVNkVTVXWjNoU1NFcGhZVzVOY2xWc1JYcGthMnhVWkZSV2VHTXdWbE5YYmtKS1pEQXhiVlpITVRCaWEyUlZZVEIwYVZrelNuRlZSWFJaVkZSR2RsVnJXVFZPUmxGNlYyeFZkbU5JWkZwalJVa3pVMnR3TTAxSVJqUmxha3AyVVZWa1ZsSkVSbmhrZWxWNlZVWmtiVlZWT1hSWGJIQlZWRzFzTkZaRVRrbFZSbEpaVkc1V1YxSnRSbkZYVlZGMlZURm9hbFpZYUZKa2EyUXlaRk01U1dWWWNEVldNbHB5VlcwMVFtTkZTbHBOUmxKdlVqSmtUMUpITUhKa00wVXdWa1V4YWxremFHRlNlbXd6VjBoS2FWSkhNWEpUVjJSeFUxaEdTRlZwT1VkVE1rbDZVVE5zUzBzeFFsSk5VM1JEVkVjd01sSXpiRmRoTUU1T1ZURnNkMXBHUW1GWk0yeFFUVmhhTVU5WVVtdE5SR2hRWXpCd2JWTlhXa05TV0VwSVUyeGtWRnBIYUVKVU1FbDVXakF4YTA1cmQzcGlia2sxWVc1a1VsRXhSa3RpVlRWcFZGVTFkR05JYkZCT2EzQlRXVmhTTWs5VmRERmplbWh2WTBoV1QxZHJTbkJVYm1oMlRtNW9kRll4WkU5V2JHTXhaRVphVEdReU5YbFhTRVpWVkZWNFNHTllTWHBVUkdSNlZWaGplV1JYYkRSU2JFMHhZa2RzTkZReFRsTmpWekZHVWtoc1dWTlhOVnBMTUhSWlVqSndhazB4VGxST1IwNUNUREJ3ZVZsdGREQlRWVkp3VTBoYWRGTlhlRUpOTVVGMlQwaEZlRlZWUms1U01sSlNUak53U1ZWdGVFaE1NakF5WkROR2VGSlhWWGxWTWxKWVZqQnNhMXA2YUc1VGJUbHFVVzFPUTFORmJGQmhNRnBvVWpKU1RGUXpVWHBoYkdSQ1kyNXdTVTVJVWxGbFZWazFWbFZLYkdOWVFtRmFibTgwVFhwYVVtTlZSakZpYWxrMFdtMXNNRTFXWkhaUk1ERmFZMFJPVTFWWFRtMU5iV2hYUzNrNU1GWlZjRVZTVlZKWVV6TkNRbE5HVW5OU1IxbHlXVzFPYUU5SVRtbE9SRXBhVGxod2VsVjZXbnBhVjNCMVZUSndUVm95U1haWmFrSlpZakpKZUZkSFVrWlJWMUp6V1hwV1lVOUZTbmROYkZwU1RETmpOV1ZzUm1salNGWTBWVmhDY1ZGWGRHMVZhMVphVmtWc1dsSXlaRVpTVkVaYVRtMXNVVlpYYXpGUlYxSXhZWHBCTUU1NmJHeFhSRUpOVTFSYU5FeDZXakJUYTBZelRtcHNlR1J1VmtwaGFtUktUMFpKTVU1SFJsVmtNRzh4VTJwU2JGcFVXbUZhTW1ob1kwWndRbVZVUmpCT1ZrWXdUbXRXU21KVlpISmhiVVpVWWtkd2JXRnNTa05qUlZVMVpVaEtjMXBzVG5WVVJFNVhVVzFvYlZadVRtcFVSRXBKWkZaR2EyTnFaRFJhYVhReVUwZGthMVpFWkRaVVJHUk1aV3QwVGxSWVpGTmtNakZTV1hwWmRtRklhRTlaVjBwWFQwVldlVnBxUWxGTlNHaFFWakJTYjFkRVNtaGpTRUowVjFaa1NWTkhNVzlXYlhSYVdURmFUbVJEY3pSV2VsSnVVMWRqT1ZCVFNYTkpiVkpvWkVkR2NscFlhMmxQYVVwQ1ZWVldRMUZWYUc5a01qQjNWMWRHU2xVd2NHeFZibEpMWWxSV2RVMVZZekprV0Vac1dsZDBXV1JYT1ZsWFJrSnNUbFpXUjFreVZUVlZia1UwVEhwRk1HUXdSa0pSVldjd1pESmFRbGRWY0V4aU1YQktZVWhhYWxSclJsSlpNR1IyVW5wb00xbHNSa3BSYTBaRlVXMDVRMW95ZEhoaFIzUndVbnBzTTAxRlNrTmtNRll6VTBka1dsTnNiRXBYYTJ4Q1ZqRldSVkZyUmtaa1ZURkRVbFZXUlZSSFVsTmFWMVpDVG01YVNWSnVjREJPYWxwNVV6RkdTbEZyVmtwUlZHUjFUbnBzTldGWVNrcE5SWFJKVkZkbk1HTXhXbk5OVlU0MFZUQTRlbFZZYkZsTlJFcHVaVVpGZDA5R1VuVmhlbHA2Wkd0c2FFMUdaRTlpTWs1dldrVTViRmRzVGxaamFrNXdVMWQwUlU1R2JFTlJNbFpaWkVWb2RGa3dSbUZXZWxwSVlVWlNORTlXYUhaUVUwbHpTVzVhYkdOdVRuQmlNalJwVDJsSmVVbHBkMmxrU0d4M1dsTkpOa2xyVWtKV1JVWm1VekJXV2tscGQybGFXR2gzWVZoS2FHUkhiSFppYVVrMlRWUlpORTVVVlRWT1ZFVTBUMWd3UFE9PSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gameoflife
  namespace: dev-namespace
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: gameoflife
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: gameoflife
      labels:
        app: gameoflife
    spec:
      containers:
        - name: openmrs
          image: 389485504177.dkr.ecr.us-east-1.amazonaws.com/forgameoflife123:65
          ports:
            - containerPort: 8080
              protocol: TCP   
      imagePullSecrets:
        - name: key      
    