---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gameoflife
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: gameoflife
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: gameoflife
      labels:
        app: gameoflife
    spec:
      containers:
        - name: openmrs
          image: 389485504177.dkr.ecr.us-east-1.amazonaws.com/forgameoflife123:latest
          ports:
            - containerPort: 8080
              protocol: TCP        
    