---
apiVersion: v1
kind: Service
metadata:
  name: game-svc
  namespace: dev-namespace
spec: 
  type: NodePort
  selector:
    app: gameoflife
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP  